### ISSUE TITLE
2.9.5+ Opening cheat before opening the game results in signature scan issue

### ISSUE THREAD

**Issue by tsuneko** [tsuneko/Orange-Juice#10]
im sorry, i debug it at .net framework 4.7.2 on visual studio 2019 (16.6.0)  os: win10 (1909)
step:
1. open then game
2. run debug to L303 "if (SignatureScan(OrangeJuice, signatures[key]))"
3. next it will jump to else case and then error occurred

_Originally posted by @yamei333 in https://github.com/tsuneko/Orange-Juice/issues/9#issuecomment-652405062_

**Comment by tsuneko** [comment]
I will take a better look at it when I can. For now it can be avoided by opening the cheat after opening the game.

**Comment by yamei333** [comment]
> im sorry, i debug it at .net framework 4.7.2 on visual studio 2019 (16.6.0) os: win10 (1909)
> step:
> 
> 1. open then game
> 2. run debug to L303 "if (SignatureScan(OrangeJuice, signatures[key]))"
> 3. next it will jump to else case and then error occurred

ah....I know the reason for my error, the target platform must be switch to x86.
