### ISSUE TITLE
Finding offsets of event Candies (continued)

### ISSUE THREAD

**Issue by DyonisX** [tsuneko/Orange-Juice#2]
I noticed that your program is now outdated due to the christmas event patch

I tried doing how you told me to find the address of Halloween candy by finding the other 2 and getting a static address and whatnot.

I found the address of oranges : **100orange.exe+3C0E5C**
                      and x-mas candy : **100orange.exe+3C0C60**
But I'm kind of stuck as to what to actually press to find the address of the Halloween candy that's similar to these 2.
Anyway priority #1 : Could you please update your code (I guess you can use the addresses I found so it's quicker)
Priority #2 could you spare the time to show me how to actually use cheat engine to find the Hallo candy address using these 2?

**Comment by tsuneko** [comment]
I’m not at home right now and don’t have access to a computer, I’ll update this program once I’m back in a week or so. To find halloween candy just search for int values like you have done for oranges and x-mas candy, with a value of 0 (probably what you have if you can’t find it :p). What I mentioned in my last reply was that you want to look for static addresses (with an int value of 0) around the oranges and x-mas candy (which you have, so it shouldn’t be hard). Cheat engine should mark these addresses as green. Anyway orange juice is a tiny program so there shouldn’t be many of these addresses, and trial and error by changing these values from here. Just keep in mind that orange juice requires a gui refresh to update the graphical display of currency, so just press any button in the shop to do so.

**Comment by DyonisX** [comment]
So if I try to search for candies (I have 49 right now) and there's more than 1 green address, I should just trial and error each one of them until I get the right one?

**Comment by tsuneko** [comment]
Yes, had you not known any of the addresses. Since you know the addresses of the other currencies and we know that the three "event" currencies (halloween, christmas, oranges) have very close addresses, you should be able to pinpoint the correct address without any use of trial or error. Finding the offset of stars given the other three addresses would be a different matter since it's address is a little further away, but that's only with a single "scan".
