### ISSUE TITLE
How safe is this if you go completely offline before using it?

### ISSUE THREAD

**Issue by Shigakuresama** [tsuneko/Orange-Juice#6]
I saw the comment on first page,  but, can anyone confirm this wont get me vac banned?, I would truly love to have everything as soon as possible, but I'm still worried about being vac banned.

**Comment by tsuneko** [comment]
VAC only really applies to multiplayer games, all the currencies modified by this cheat are stored in your save file and don’t interact with steam or OJ’s servers. I have the VAC message written as a disclaimer, and honestly no one should be banned for using this. It does not offer any “cheat-like” advantages to online play after all, and should really be treated similarly to downloading a complete game save.
