### ISSUE TITLE
no xmas candy?

### ISSUE THREAD

**Issue by DiablaYukki** [tsuneko/Orange-Juice#7]
i get why they are under appreciated but i think it would still be nice.

**Comment by tsuneko** [comment]
Are xmas candies even in the store anymore?

**Comment by DiablaYukki** [comment]
Not at the moment , the skins are though unlike the valentines ones. So i
would assume its possible or it might delete the currency after the event.
Just got back into playing so i dont have any currency to know

**Comment by tsuneko** [comment]
Okay, I will have a look when I’m home in a few hours

**Comment by tsuneko** [comment]
I've confirmed that christmas candies are depreciated through checking the store on a fresh account, and also by checking previous offsets.

What you are looking at must be the christmas wreaths - those were only obtainable in the 2018 christmas event and are synced to steam's servers, so I cannot modify them (like arcade tokens).

**Comment by tsuneko** [comment]
In the [1.31.3 patch notes](https://100orangejuice.gamepedia.com/Version_1.31.3), 

> The old Xmas and Halloween costumes can now be bought for characters whose DLC you don't own (**in preparation of removing the related currencies**; if you have event currency but don't have all the costumes, make sure to spend it now).

So basically the devs are migrating the existing currencies onto the steam inventory API, and this cheat isn't able to interact with that.

**Comment by DiablaYukki** [comment]
Dang well thanks for the info. Atleast you tried.
