### ISSUE TITLE
Incorrect signature for Stars following 2.9.5 Update

### ISSUE THREAD

**Issue by hellotinh03** [tsuneko/Orange-Juice#9]
The program isn't working anymore, I guess Fruitbat changed signatures.

**Comment by tsuneko** [comment]
I'll test it when I can thanks.

**Comment by tsuneko** [comment]
Fixed in new version

**Comment by yamei333** [comment]
signatures was changed in 2.9.7

**Comment by tsuneko** [comment]
Seems to be a bug with opening the cheat before opening the game. The signatures are correct however.

**Comment by yamei333** [comment]
im sorry, i debug it at .net framework 4.7.2 on visual studio 2019 (16.6.0)
step:
1. open then game
2. run debug to L303 "if (SignatureScan(OrangeJuice, signatures[key]))"
3. next it will jump to else case and then error occurred
